CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       varchar(100)                            NOT NULL,
    email      varchar(100)                            NOT NULL,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp DEFAULT (now()),

    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       varchar(100)                            NOT NULL,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp DEFAULT (now()),

    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              varchar(100)                            NOT NULL,
    annotation         varchar(100)                            NOT NULL,
    category_id        bigint                                  NOT NULL,
    description        text,
    event_date         timestamp                               NOT NULL,
    lat                float,
    lon                float,
    paid               boolean,
    participant_limit  int       DEFAULT 0,
    request_moderation boolean,
    initiator_id       bigint                                  NOT NULL,
    published_on       timestamp,
    state              varchar(50)                             NOT NULL,
    created_at         timestamp DEFAULT (now()),
    updated_at         timestamp DEFAULT (now()),

    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT FK_EVENT_ON_USER FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      varchar(100)                            NOT NULL,
    pinned     boolean,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp DEFAULT (now()),

    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id bigint                                  NOT NULL,
    event_id       bigint                                  NOT NULL,
    created_at     timestamp DEFAULT (now()),
    updated_at     timestamp DEFAULT (now()),

    CONSTRAINT pk_compilation_event PRIMARY KEY (id),
    CONSTRAINT FK_COMPILATION_EVENT_ON_COMPILATION FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT FK_COMPILATION_EVENT_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     bigint                                  NOT NULL,
    requester_id bigint                                  NOT NULL,
    status       varchar(50)                             NOT NULL,
    created_at   timestamp DEFAULT (now()),
    updated_at   timestamp DEFAULT (now()),

    CONSTRAINT pk_participation_request PRIMARY KEY (id),
    CONSTRAINT FK_PARTICIPATION_REQUEST_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_PARTICIPATION_REQUEST_ON_USER FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    varchar(250)                            NOT NULL,
    status     varchar(50)                             NOT NULL,
    user_id    bigint                                  NOT NULL,
    event_id   bigint                                  NOT NULL,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp DEFAULT (now()),

    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT FK_COMMENT_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);
