CREATE TABLE IF NOT EXISTS stats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        varchar(50)                             NOT NULL,
    uri        varchar(150)                            NOT NULL,
    ip         varchar(16)                             NOT NULL,
    created_at timestamp DEFAULT (now()),
    updated_at timestamp DEFAULT (now()),

    CONSTRAINT pk_stat PRIMARY KEY (id)
);